site_name: Metrics Documentation
site_url: "http://metrics.operas-eu.org/"

extra_css:
  - css/css.css?v=1.0
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css?v=1.0

extra_javascript:
  - js/publishers.js?v=1.0.1
  - js/service-worker.js

plugins:
  - awesome-pages

use_directory_urls: true

theme:
  name: material
  custom_dir: overrides
  logo: /images/logo.png
  favicon: /images/icons/Operas-icon.png

  palette:
    
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      accent: purple
      # primary: custom
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: purple
      # primary: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: white
      accent: purple
      # primary: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


  features:
    - content.code.annotate
    - navigation.tabs
    - navigation.top
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tracking
  color_mode:
    default: light  # or "dark" or "auto"
    toggle: true
  toc:
    depth: 3  # Display up to h3 headers      

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/hirmeos
  awesome_pages:
    use_trailing_slash: false
  version: !ENV [GITHUB_SHA, 'random']
     
copyright: "<a href='https://operas-eu.org/' target='_blank'><img src='/images/logo.png' width='200'></a>
<p>Unless otherwise indicated, all materials created by the Hirmeos Project are licensed under a 
<br><a href='https://creativecommons.org/licenses/by/4.0/'>Creative Commons Attribution 4.0 International License</a>. 
Privacy policy - <a href='https://metrics.operas-eu.org/acceptable-use-policy'>Acceptable Use Policy and Conditions of Use</a></p>
"

nav:
  - '<i class="fa-solid fa-chart-line"></i>&nbsp;&nbsp;Measures': measures.md
  - '<i class="fa-sharp-duotone fa-solid fa-heart"></i>&nbsp;&nbsp;Our Principles': principles.md
  - '<i class="fa-solid fa-book-open"></i>&nbsp;&nbsp;Documentation':
      - Getting Started: metrics-docs/getting-started.md
      - Altmetrics: metrics-docs/altmetrics.md
      - Annotation: metrics-docs/annotation.md
      - Countries API: metrics-docs/countries-api.md
      - Crossref Cited-by: metrics-docs/crossref-citedby.md      
      - OPERAS Metrics Overview: metrics-docs/overview.md
      - Drivers: metrics-docs/drivers.md      
      - Onboarding Users: metrics-docs/onboarding-users.md
      - Onboarding Metrics: metrics-docs/onboarding-sending-metrics.md
      - Metrics API: metrics-docs/metrics-api.md
      - Drivers & Plugins:
          - Access Logs: metrics-docs/access-logs-local.md 
          - Google Analytics: metrics-docs/google-analytics.md
          - Google Books: metrics-docs/google-books.md
          - Identifier Translation Service: metrics-docs/identifier-translation-service.md
          - IRUS-UK: metrics-docs/irus-uk.md
          - JSTOR: metrics-docs/jstor.md
          - Matomo: metrics-docs/matomo.md
          - Onboarding Sending Metrics: metrics-docs/onboarding-sending-metrics.md
          - Onboarding Users: metrics-docs/onboarding-users.md
          - Server Access Logs: metrics-docs/server-access-logs.md
          - Tokens API: metrics-docs/tokens-api.md
          - Unglue.it: metrics-docs/unglueit.md
          - Figshare: metrics-docs/figshare.md
      - Widget: metrics-docs/widget.md
      - Publishers: metrics-docs/publishers.md
docs_dir: docs
